PBI: 11122875: Add PR Validation Workflow to Widgets CR: (pull request).
Add validation to pull requests in Widgets repo.

Changes
1) Add .github/workflows/webpack.yml to run lint, build and test on pull
requests, for Node 12.x, 14.x and 16.x.
2) Node 12.x and 14.x worked fine out of the box, but Node 16.x needed
tweaking. Specifically:
3) Node 16.x has a new lockfileVersion of 2 and did not work with the
existing package-lock.json (I was getting E401 authentication
failures, even though we were just using the public registry, which
should not have needed any authentication). The only way I could get
past this was to delete package-lock.json and regenerate it.
4) Unfortunately, this resulted in upgrades of various packages. I ended
up having to roll some of these back. Specifically:
5) When Typescript upgraded from 4.2.4 to 4.4.3, we got build errors
because the catch block in try-catch now assigns a type of "unknown"
instead of "any". After I fixed this, it built fine, but then test
failed during the typescript compilation phase in test, because of the
@microsoft/fast-foundation, fast-element, etc. typescript typings. An
example complaint was, "error TS2320: Interface 'Anchor' cannot
simultaneously extend types 'HTMLElement & FASTElement' and
'DelegatesARIALink'. Named property 'ariaAtomic' of types 'HTMLElement &
FASTElement' and 'DelegatesARIALink' are not identical.". I did try
rolling the @microsoft/fast* packages back, but the problem persisted. I
gave up and rolled Typescript back to 4.2.4.
6) Despite rolling Typescript back, I am keeping the fixes for the catch
blocks.

Known Issues
1) On my Windows dev box with WSL2, Node 16.x, npm run test fails for me
because of @web/test-runner-playwright. Not sure if the earlier Node
12.x and 14.x would have passed, I normally use Windows and Node 12.x.
The GitHub machines are probably running native Linux, and npm run
test seems to succeed there.

Testing Procedure
1) Submit a PR which you know will break in install, lint, build or test
(preferably each one separately). Confirm PR shows validation
failure. Note that I didn't try this and I also don't know if the
policies are set to reject the PR if validation fails.